\newpage{}

## 员工信息管理系统的问题 {#problems-building-simple-db}

\markboth{员工信息管理系统的问题}{员工信息管理系统的问题}

在前文，我们一起实现了一个简单的员工信息管理系统。尽管这个数据库能够满足基本的功能需求，但它不可否认地存在一些缺陷。

在本文中，我会罗列这个信息管理系统可能出现的一些问题，并通过将这些问题分类，来识别数据库系统所做的工作、提供的保证：

### 与物理存储结构绑定的查询和写入逻辑 {-}

- 没有一种通用的查询语言，每个查找需求都需要编写单独的查找方法

- `findByName` 方法、`write` 方法都直接与底层的数据存储方式耦合，查找数据的逻辑竟然需要精确到读取第几个字段，这是一种命令式 (imperative) 的做法，与目前的 SQL 语言的声明式查询是相对的，命令式的查询语言将底层实现暴露给最终用户，使得查询语言与底层实现耦合，这在日后是维护的噩梦

### 缺乏并发控制，读写操作互相排斥 {-}

- 数据库在写入的时候缺乏并发控制，可能出现两个进程同时写入一个文件的情况，造成文件损坏

- `findByName` 方法同样不是并发安全的，可能在一个进程读取文件时另一个进程将文件 `rewind` 

- 由于直接依赖底层文件的指针位置，读写无法同时进行

### 数据持久化与数据完整性检查 {-}

- 若在执行 `write` 方法的时候，`flush` 的时候系统断电，则会导致数据文件损坏，缺乏错误检查机制

- 若在执行 `write` 时，系统完成了 `write` 操作还没有flush时系统断电，会造成数据完全丢失

### 缺乏唯一索引约束能力 {-}
- `write` 方法缺乏对记录的唯一性校验，如果用户犯错，系统就会写入多条相同的记录

### 性能问题 {-}

- `findByName` 方法异常低效，每次都需要遍历整个文件查找记录，也不具备自己的缓存

### 缺乏字段类型、数据格式和存储低效 {-}

- 数据文件对数据格式缺乏校验和表示，写入的所有东西都会变成 string

- 数据文件用的是文本格式，空间效率十分低下

### 缺乏表结构灵活性 {-}

- 如果要新增一个员工性别字段怎么办？之前的数据如何迁移？

尽管提出了许多问题，且似乎每一个这些问题都有简单的解决方式，但若要考虑一个能够解决所有问题的方案，似乎问题就会变得复杂。

举例来说，如果是为了解决缺乏唯一索引的问题，我们可以实现一个方法，在写入数据前先遍历整个文件，看看是不是有重复的数据，如果有的话就拒绝写入。但这样的实现也会让写入的性能进一步下降。

那么，有没有什么办法可以比较好地解决上面的全部问题呢？其实是有的。为了解决上面的问题，需要引入现代数据库系统的多个概念。从下一篇文章开始，我就会开始介绍数据库系统中的关键概念，并看看我们如何利用这些工具来解决上面的问题。
