\newpage{}

# DBMS简介 {#intro-to-dbms}

## 数据库系统发展简史 {#brief-history-of-dmbs}

在 1960 年代，计算机刚被发明不久，当时计算机远没有普及，软件生态相较今天也十分简单。但在当时，就已经有大型公司尝试着使用计算机来管理数据了。

使用计算机来管理数据有很多好处，相较于传统的纸质数据管理方式，计算机一次性能够记录更多的数据，在数据的检索和管理上也更为容易，存在数据更不容易丢失等优势。

1960 年代主要的数据库系统是以 IDS 为代表的层级数据库。这么说可能会让读者没有概念，因此，为了描述数据库系统，我首先展开一下数据库系统的几个基本概念。

### 数据模型 {#datamodel}

所有的数据存储都依赖一个事先定义好的数据模型。以大家熟悉的 MySQL 举例，MySQL 是一种关系型数据库管理系统 (Relational DBMS) 。 MySQL 的数据模型是基于关系代数建立的，在 MySQL 中，所有的数据都从属于一个“表”，这个“表”可以与其他“表”进行关系代数运算。这就是一种非常典型的数据模型。

#### 层级数据库 {#hierarchical-database}

最早期的数据库大部分都是层级数据库 (Hierarchical Database)，在层级数据库中，所有的数据都是按照层级组织的。通常来说，这种类型的数据库中都有一个根结点，当用户需要寻找什么数据的时候，需要手动操作数据库，从根结点出发，定位到自己想要的数据。

举例来说，如果要存储书和作者的关系，可能看起来是下面这样：

```
RECORD Author
    AuthorID: INTEGER
    Name: STRING
    Birthdate: DATE
    Books: SET OF Book

RECORD Book
    BookID: INTEGER
    Title: STRING
    PublicationDate: DATE
    Author: REFERENCE TO Author

// 定义作者
AUTHOR_1 = Author(AuthorID=1, Name="J.K. Rowling", Birthdate="31/07/1965")
AUTHOR_2 = Author(AuthorID=2, Name="George Orwell", Birthdate="25/06/1903")

// 定义书
BOOK_1 = Book(BookID=1, Title="Harry Potter and the Sorcerer's Stone", PublicationDate="26/06/1997", Author=AUTHOR_1)
BOOK_2 = Book(BookID=2, Title="1984", PublicationDate="08/06/1949", Author=AUTHOR_2)

// 通过这种方式将作者和书链接起来
AUTHOR_1.Books = [BOOK_1]
AUTHOR_2.Books = [BOOK_2]

// 查询的例子

// 找到所有AUTHOR_1写的书
for book in AUTHOR_1.Books:
    print(book.Title)

// 获取BOOK_2的作者名
print(BOOK_2.Author.Name)
```

可以看到，在这种数据模型下，用户需要手动跟踪数据中存储的指针，直到找到自己的数据位置

1960 年代时，主要的数据库就是这种形式。这种形式的数据库中查询数据很复杂，和关系型数据库相比，不仅不能一次性使用外键连接多个表，而且查询数据的方式主要依赖代码实现，很难让用户单独使用命令查询。

在 1970 年代，随着关系代数的论文被发表，关系型数据库的概念开始兴起。我们今天所熟悉的 SQL 也被发明了。 IBM 的 System R 是第一个实现了关系代数模型的数据库产品。不过，由于当时的计算机尚未普及，对数据库系统系统的需求基本还停留在大型公司，其他大部分公司没有对数据库产品的需求。但 1970 年代的意义是重大的，因为关系型数据库这一时至今日仍然流行的数据模型就是在那时被确立的。

当然，尽管有了关系型数据库的雏形，当时的数据库系统还有很多基础研究没有完成。举例来说，对于数据库系统应该如何处理并发请求，如何管理锁来避免用户数据出现问题，直到 1990 年代才有系统性的论文出现。

随着计算机和互联网的普及，数据库系统不再是单纯的为大公司服务的昂贵系统，举例来说，1995 年微软发布了 Microsoft SQL Server ，这是一款能够运行在普通个人计算机上的数据库管理系统，而随着互联网的发展，越来越多的网站被建立起来，对数据库系统的需求激增，因此，以 MySQL 、MsSQL 、Postgres 等为代表的可以运行在普通个人计算机上的数据库系统从 1990 年代开始流行。

#### 关系型数据库 {#relational-database}

在 1990 年代流行的数据库就是关系型数据库了，这个时候的数据库已经和今天大家熟悉的数据库很相似，我就不多做介绍。需要指出的是，今天大家很熟悉的 MySQL 在当时功能十分简单，是一个类似 KV数据库 的数据库。在 Innobase 将 innodb 捐献给 MySQL 之后， MySQL 才拥有了今天这些大家熟悉的功能。在 InnoDB 之前， MySQL 的默认存储引擎 MyISAM 不支持外键这种基本的关系型数据库功能，也不支持行锁这种基础的并发控制，是一个功能相对较弱的数据库。

#### NoSQL与NewSQL {#newsql}

在关系型数据库流行之后，随着互联网的进一步发展，对数据库系统也提出了新的要求，例如，非结构化数据存储，或者是大量数据的分区存储、分析能力，这些不是传统的关系型数据库能够支持的。因此，随后的数据库发展朝着两个方向进行：

第一个方向是发明各种新型的数据模型，例如文档数据库、图数据库，这些基于特定数据模型的数据库在特定的应用场景下相较关系型数据库有更大的优势。

第二个方向是进行数据库架构的演变，以支持不同的场景和灵活的性能要求，例如 Google 的 Spanner 就是典型的一种分布式、超大型数据库。
